### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/twintip-spring-web#1]
Hi there--is this project currently in use at Zalando? Are you planning to develop this further?

**Comment by jhorstmann** [comment]
Yes, it's in use by several of our components. Apparently it's working so well that we did not require any changes in the last 6 months :)

**Comment by lukasniemeier-zalando** [comment]
but iirc there is a equivalent solution from the STUPS team

**Comment by LappleApple** [comment]
@lukasniemeier-zalando do you know which is? Also wondering + @whiskeysierra if we can move this to the Incubator, because it's quite Zalando-centric given the STUPS ties.

**Comment by LappleApple** [comment]
@lukasniemeier-zalando @AlexanderYastrebov @whiskeysierra @kode4food Can we move this to the Incubator? See comment above this one :)

**Comment by lukasniemeier-zalando** [comment]
If we see STUPS as too Zalando-centric, then yes!

**Comment by LappleApple** [comment]
OK, let's move it then :)

**Comment by LappleApple** [comment]
@lukasniemeier-zalando @AlexanderYastrebov @whiskeysierra @kode4food It would actually make more sense to move this to the zalando-STUPS URL, to keep all STUPS-related projects there. WDYT?

**Comment by whiskeysierra** [comment]
That would require to handover ownership to the STUPS teams, wouldn't it?

**Comment by LappleApple** [comment]
@whiskeysierra Nah -- they can grant you/the team admin privileges.

**Comment by LappleApple** [comment]
@whiskeysierra Henning says he'll make the transfer to the STUPS URL no problem

**Comment by whiskeysierra** [comment]
👍

**Comment by LappleApple** [comment]
@hjacobs Hi Henning, please transfer this repo to the STUPS URL as per above and add these guys as admins for the repo: @lukasniemeier-zalando @AlexanderYastrebov @whiskeysierra @kode4food. Thanks!

**Comment by hjacobs** [comment]
done: https://github.com/zalando-stups/twintip-spring-web
